esphome:
  name: doorbell

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'Doorbell'
    password: !secret ap_password

captive_portal:

switch:
  - platform: gpio
    name: 'Gong'
    pin: GPIO12
    id: gong
    internal: True

button:
  - platform: template
    name: 'Doorbell'
    id: doorbell
    on_press:
      - switch.turn_on: gong
      - delay: 300ms
      - switch.turn_off: gong
